version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
      install:
        - method: setuptools
          path: .
    #
  apt_packages:
    - gfortran

sphinx:
  configuration: doc/sources/conf.py

#python:
#  version: 3.8
#  install:
#    - method: setuptools
#      path: .
#
## 시스템 패키지 설치
#build:
#  apt_packages:
#    - gfortran

