version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
    #apt_packages:
    #ap- gfortran

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - method: setuptools
      path: .
    - requirements: docs/requirements.txt

## 시스템 패키지 설치
#build:
#  apt_packages:
#    - gfortran

