version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

sphinx:
  configuration: doc/sources/conf.py

python:
  install:
    - method: setuptools
      path: .

# 시스템 패키지 설치
build:
        apt_packages:
                - gfortran

