"""
This file is automatically generated from IDL files.
"""

class veluga:
    def r_gal():
        """
        This method retrieves galaxy or halo catalog data for a given snapshot and object ID.
        
        Parameters
        ----------
        snap0 : int
        	Snapshot number
        
        id0 : int
        	Object ID. Use a negative value to retrieve all objects in the snapshot.
        
        horg: string
        	A flag to specify the object type. Galaxy for 'g' and Halo for 'h'
        	Default is 'g'
        
        
        Returns
        -------
        Structured_array
        	A structured array containing information about the objects.
        
        Examples
        --------
        IDL> g = veluga->r_gal(100, 1)
        		Read the galaxy with ID=1 at the snapshot of 100
        
        IDL> PRINT, g[0].ID
        		Print its ID
        
        IDL> h = veluga->r_gal(200, -1, horg='h')
        		Read all halos at the snapshot of 200
        
        IDL> PRINT, h[0].mvir
        		Print the virial mass of the first halo

        """
        pass

    def r_part():
        """
        This method retrieves particle information of a given galaxy or halo
        
        Parameters
        ----------
        snap0 : int
        	Snapshot number
        
        id0 : int
        	Object ID.
        
        horg: string {'h' or 'g'}
        	A flag to specify the object type. Galaxy for 'g' and Halo for 'h'
        	Default is 'g'
        
        g_simunit: boolean
        	If set (/g_simunit), return output unit as the ramses simulation unit
        
        g_ptime: boolean
        	If set (/g_ptime), retrieve physical time unit for the age of particles
        	Stored in gyr, sfact, and redsh tag
        
        
        Returns
        -------
        Structure
        	xx, yy, zz : [kpc (physical)]
        		position of particles
        	vx, vy, vz : [km/s]
        		velocity of particles
        	mp : [Msun]
        		mass of particles
        	ap : [simulation unit]
        		birth time
        	zp : []
        		metallicitiy
        	gyr : [Gyr]
        		birth time in Gyr (retrieved if g_ptime=True)
        	sfact: []
        		birth time in scale factor (retrieved if g_ptime=True)
        	redsh: []
        		birth time in redshift (retrieved if g_ptime=True)
        	id : []
        		Particle ID
        	domain : []
        		mpi domain number to which particles belong
        	KE : [km^2/s^2]
        		specific Kinetic energy
        		retrieved when g_potential is called (Not implemented yet)
        	UE : [km^2/s^2]
        		specific Internal energy
        		retrieved when g_potential is called (Not implemented yet)
        	PE : [km^2/s^2]
        		specific Potential energy
        		retrieved when g_potential is called (Not implemented yet)
        
        Examples
        --------
        IDL> g = veluga->r_part(100, 1)
        		Retrieve information of the member star particle of the galaxy with ID=1 at the snapshot of 100
        
        IDL> PRINT, g[0].ID
        		Print ID of the first particle
        
        IDL> g = veluga->r_part(100, 10, horg='g', /g_ptime)
        		Retrieve information of the member star particles (including their birth time properties) that belong to the galaxy with ID=10 at the snapshot of 100
        
        IDL> h = veluga->r_gal(200, 5, horg='h')
        		Retrieve information of the member DM particle of the halo with ID=5 and snapshot=200
        
        IDL> ; extract particles with an index
        
        IDL> g = veluga->r_part(100, 10, horg='g', /g_ptime)
        IDL> index = WHERE(g.gyr LT 1.)
        IDL> g_new = veluga->g_extract(g, index)
        	Return a new structure with a given index

        """
        pass

